# Generated by Django 2.2.26 on 2022-03-26 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('entryPrice', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('noOfRooms', models.PositiveIntegerField(default=1)),
                ('openingHours', models.TextField(default='Monday:\nTuesday:\nWednesday:\nThursday:\nFriday:\nSaturday:\nSunday:', max_length=500)),
                ('averageOverallRating', models.FloatField(default=0)),
                ('instagram', models.URLField(default='https://www.instagram.com')),
                ('facebook', models.URLField(default='https://www.facebook.com')),
                ('website', models.URLField(default='https://www.')),
                ('mapSrc', models.URLField(default='https://maps.google.com/maps?q=firewater&t=&z=13&ie=UTF8&iwloc=&output=embed')),
                ('about', models.TextField(default='', max_length=500)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(default=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewDate', models.DateField(default=datetime.datetime(2022, 3, 26, 18, 37, 19, 520162, tzinfo=utc))),
                ('drinksPrice', models.IntegerField(default=1)),
                ('typeOfCrowd', models.CharField(max_length=30)),
                ('popularNight', models.CharField(max_length=9)),
                ('avgQueueTime', models.IntegerField(default=0)),
                ('staffFriendliness', models.IntegerField(default=1)),
                ('qualityOfSafety', models.IntegerField(default=1)),
                ('overallRating', models.IntegerField(default=1)),
                ('additionalComments', models.CharField(default='', max_length=1000)),
                ('reviewLikes', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubScoutGlasgow.Club')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubScoutGlasgow.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ClubImages/')),
                ('url', models.CharField(default='images/ClubImages/', max_length=500)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ClubScoutGlasgow.Club')),
            ],
        ),
    ]
