# Generated by Django 2.2.26 on 2022-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0002_auto_20220310_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='url',
        ),
        migrations.AddField(
            model_name='club',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
    ]
