# Generated by Django 2.2.26 on 2022-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0003_auto_20220310_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
