# Generated by Django 2.2.26 on 2022-03-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0004_club_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='openingHours',
            field=models.CharField(max_length=500),
        ),
    ]
