# Generated by Django 2.2.26 on 2022-03-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0005_auto_20220315_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='entryPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(default='https://www.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='club',
            name='noOfRooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(default='https://www.instagram.com'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ClubScoutGlasgow.Club')),
            ],
        ),
    ]
