# Generated by Django 2.2.26 on 2022-03-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0006_auto_20220316_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubimage',
            name='url',
            field=models.ImageField(default='static/images/ClubImages/hive1.jpeg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(default='https://www.'),
        ),
        migrations.AlterField(
            model_name='clubimage',
            name='image',
            field=models.ImageField(upload_to='static/images/ClubImages/'),
        ),
    ]
