# Generated by Django 2.2.26 on 2022-03-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0007_auto_20220316_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubimage',
            name='url',
        ),
    ]
