# Generated by Django 2.2.26 on 2022-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0008_remove_clubimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubimage',
            name='url',
            field=models.CharField(default='images/ClubImages/<django.db.models.fields.files.ImageField>', max_length=500),
        ),
    ]
