# Generated by Django 2.2.26 on 2022-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0009_clubimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='openingHours',
            field=models.TextField(default='Monday:/nTuesday /n Wednesday /n', max_length=500),
        ),
        migrations.AlterField(
            model_name='clubimage',
            name='url',
            field=models.CharField(default='images/ClubImages/', max_length=500),
        ),
    ]
