# Generated by Django 2.2.26 on 2022-03-21 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0011_alter_club_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
    ]
