# Generated by Django 2.2.26 on 2022-03-21 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0012_review_reviewdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='url',
        ),
        migrations.AlterField(
            model_name='review',
            name='additionalComments',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='drinksPrice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='overallRating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='qualityOfSafety',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 21, 14, 12, 20, 669135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='staffFriendliness',
            field=models.IntegerField(default=1),
        ),
    ]
