# Generated by Django 2.2.26 on 2022-03-21 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0013_auto_20220321_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 21, 14, 12, 42, 771612, tzinfo=utc)),
        ),
    ]
