# Generated by Django 2.2.26 on 2022-03-22 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0014_auto_20220321_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 11, 34, 56, 187177, tzinfo=utc)),
        ),
    ]
