# Generated by Django 2.2.26 on 2022-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0015_auto_20220322_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(),
        ),
    ]
