# Generated by Django 2.2.26 on 2022-03-22 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0017_auto_20220322_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 11, 58, 2, 944018, tzinfo=utc)),
        ),
    ]
