# Generated by Django 4.0.3 on 2022-03-22 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0022_alter_review_reviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 19, 5, 44, 66588, tzinfo=utc)),
        ),
    ]
