# Generated by Django 2.2.26 on 2022-03-24 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0024_alter_review_reviewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='mapSrc',
            field=models.URLField(default='https://maps.google.com/maps?q=firewater&t=&z=13&ie=UTF8&iwloc=&output=embed'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 16, 53, 54, 351802, tzinfo=utc)),
        ),
    ]
