# Generated by Django 2.2.26 on 2022-03-25 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0025_auto_20220324_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 15, 35, 21, 487432, tzinfo=utc)),
        ),
    ]
