# Generated by Django 3.2.3 on 2022-03-24 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0025_auto_20220324_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 17, 18, 46, 292749, tzinfo=utc)),
        ),
    ]
