# Generated by Django 3.2.3 on 2022-03-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0026_alter_review_reviewdate'),
        ('ClubScoutGlasgow', '0026_auto_20220325_1535'),
    ]

    operations = [
    ]
