# Generated by Django 3.2.3 on 2022-03-25 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0027_merge_20220325_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='menu',
            field=models.FileField(default='', upload_to='static/Menu/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 18, 53, 17, 360989, tzinfo=utc)),
        ),
    ]
