# Generated by Django 3.2.3 on 2022-03-26 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow','0027_merge_20220325_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 3, 4, 44, 784829, tzinfo=utc)),
        ),
    ]
