# Generated by Django 2.2.26 on 2022-03-26 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0028_auto_20220325_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='menu',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 16, 0, 53, 832246, tzinfo=utc)),
        ),
    ]
