# Generated by Django 2.2.26 on 2022-03-26 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0029_auto_20220326_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='clubimage',
            name='image',
            field=models.ImageField(upload_to='images/ClubImages/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='additionalComments',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 18, 12, 31, 677128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
