# Generated by Django 2.2.26 on 2022-03-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0030_auto_20220326_1812'),
        ('ClubScoutGlasgow', '0026_auto_20220325_1310'),
    ]

    operations = [
    ]
