# Generated by Django 3.2.3 on 2022-03-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0028_auto_20220325_1853'),
        ('ClubScoutGlasgow', '0030_auto_20220326_1812'),
    ]

    operations = [
    ]
