# Generated by Django 3.2.3 on 2022-03-27 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0031_merge_0028_auto_20220325_1853_0030_auto_20220326_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='menu',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 11, 16, 41, 751148, tzinfo=utc)),
        ),
    ]
