# Generated by Django 3.2.3 on 2022-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubScoutGlasgow', '0031_merge_20220327_1125'),
        ('ClubScoutGlasgow', '0032_auto_20220327_1116'),
    ]

    operations = [
    ]
